steps:
  # Step to run tests for the server
  # - name: 'test'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       npm install && \
  #       PORT=5000 \
  #       MONGODB_URL=ongodb://todo-mongo-service:27017/todo-app/test-database \
  #       JWT_SECRET=your-test-jwt-secret \
  #       npm run test
  #   dir: '.'
  # Build the Docker image for the server app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'gcr.io/devops-384013/todo-server-app:latest', '.']
    dir: '.'

  # Push the Docker image for the server app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devops-384013/todo-server-app:latest']

  # Authenticate with GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'autopilot-cluster-1', '--region', 'europe-central2-a', '--project', 'devops-384013']

  # Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'YAML/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-central2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
      - 'REACT_APP_baseAPIURL=http://www.devops-tutorial.site'

images:
  - 'gcr.io/devops-384013/todo-server-app:latest'
