apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-todo-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: devops-todo
  endpoints:
  - targetPort: 5000 
    path: /api/metrics
