apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjusted to ReadWriteOnce for compatibility
  resources:
    requests:
      storage: 1G
  # It's okay to omit storageClassName to use the default provisioning.
